/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.clinicaVeterinaria.view;

import Controle.ControleAnimal;
import Controle.ControleCliente;
import Modelo.ModeloAnimal;
import Modelo.ModeloCliente;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alessandro
 */
public class TelaVeterinario extends javax.swing.JFrame {

    /**
     * Creates new form TelaVeterinario
     */
    public TelaVeterinario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jbVerConsulta = new javax.swing.JButton();
        jbVerRelatório = new javax.swing.JButton();
        jbAtenderAnimal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jbPesquisarAnimal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmRelatorio = new javax.swing.JMenu();
        jmRelatorioCriar = new javax.swing.JMenuItem();
        jmRelatorioAlterar = new javax.swing.JMenuItem();
        jmRelatorioVisualizar = new javax.swing.JMenuItem();
        jmVerConsulta = new javax.swing.JMenu();
        jmSobre = new javax.swing.JMenu();
        jmAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Veterinário");
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jbVerConsulta.setText("Ver Consultas");
        jbVerConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerConsultaActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbVerConsulta);
        jbVerConsulta.setBounds(10, 112, 190, 40);

        jbVerRelatório.setText("Ver Relatório");
        jbVerRelatório.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerRelatórioActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbVerRelatório);
        jbVerRelatório.setBounds(320, 110, 190, 40);

        jbAtenderAnimal.setText("Atender Animal");
        jbAtenderAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtenderAnimalActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbAtenderAnimal);
        jbAtenderAnimal.setBounds(320, 50, 190, 40);
        jDesktopPane1.add(jSeparator1);
        jSeparator1.setBounds(0, 302, 650, 10);

        jButton5.setText("Logar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton5);
        jButton5.setBounds(539, 363, 70, 30);

        jbPesquisarAnimal.setText("Pesquisar Animal");
        jbPesquisarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarAnimalActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbPesquisarAnimal);
        jbPesquisarAnimal.setBounds(10, 50, 190, 40);

        jmRelatorio.setText("Relatórios");

        jmRelatorioCriar.setText("Criar");
        jmRelatorio.add(jmRelatorioCriar);

        jmRelatorioAlterar.setText("Alterar");
        jmRelatorioAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRelatorioAlterarActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmRelatorioAlterar);

        jmRelatorioVisualizar.setText("Visualizar");
        jmRelatorio.add(jmRelatorioVisualizar);

        jMenuBar1.add(jmRelatorio);

        jmVerConsulta.setText("Ver Consultas");
        jMenuBar1.add(jmVerConsulta);

        jmSobre.setText("Sobre");
        jMenuBar1.add(jmSobre);

        jmAjuda.setText("Ajuda");
        jMenuBar1.add(jmAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmRelatorioAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRelatorioAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmRelatorioAlterarActionPerformed

    private void jbVerConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerConsultaActionPerformed
        // TODO add your handling code here:
        TelaCadastroAnimal tca = new TelaCadastroAnimal();
        tca.setVisible(true);
    }//GEN-LAST:event_jbVerConsultaActionPerformed

    private void jbVerRelatórioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerRelatórioActionPerformed
        // TODO add your handling code here:
        TelaConsulta tc = new TelaConsulta();
        tc.setVisible(true);
    }//GEN-LAST:event_jbVerRelatórioActionPerformed

    private void jbAtenderAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtenderAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAtenderAnimalActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jbPesquisarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarAnimalActionPerformed
        // TODO add your handling code here:
        try {
        ModeloAnimal animal = new ModeloAnimal();
        ModeloCliente cliente = new ModeloCliente();
        Controle.ControleAnimal control = new ControleAnimal();
        Controle.ControleCliente controlC = new ControleCliente();
        String cpf, nomeAnimal;
            cpf=JOptionPane.showInputDialog(null, "Digite o CPF do cliente");
            if(controlC.verificarCPF(cpf)){
            nomeAnimal=JOptionPane.showInputDialog(null, "Digite o nome do Animal");
            if(control.verificarNome(nomeAnimal)){
            cliente = controlC.consultarCliente(cpf);
            animal = control.consultarAnimal(cliente.getCpf(), nomeAnimal);
            TelaAlteracaoAnimal telaAlteracaoAnimal = new TelaAlteracaoAnimal();
            telaAlteracaoAnimal.inserirDados(cliente, animal);
            telaAlteracaoAnimal.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Animal não cadastrado");
            }
            }
            else{
                JOptionPane.showMessageDialog(null, "Cliente não cadastrado");
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbPesquisarAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAtenderAnimal;
    private javax.swing.JButton jbPesquisarAnimal;
    private javax.swing.JButton jbVerConsulta;
    private javax.swing.JButton jbVerRelatório;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmRelatorio;
    private javax.swing.JMenuItem jmRelatorioAlterar;
    private javax.swing.JMenuItem jmRelatorioCriar;
    private javax.swing.JMenuItem jmRelatorioVisualizar;
    private javax.swing.JMenu jmSobre;
    private javax.swing.JMenu jmVerConsulta;
    // End of variables declaration//GEN-END:variables
}
