/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.clinicaVeterinaria.view;

import Controle.ControleAnimal;
import Controle.ControleCliente;
import Modelo.ModeloAnimal;
import Modelo.ModeloCliente;
import Modelo.ModeloRelatorios;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Alessandro
 */
public class TelaVeterinario extends javax.swing.JFrame {

    /**
     * Creates new form TelaVeterinario
     */
    public TelaVeterinario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jbVerRelatório = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jbPesquisarAnimal = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmSobre = new javax.swing.JMenu();
        jmAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Veterinário");
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jbVerRelatório.setText("Ver Relatórios");
        jbVerRelatório.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerRelatórioActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbVerRelatório);
        jbVerRelatório.setBounds(400, 50, 190, 40);
        jDesktopPane1.add(jSeparator1);
        jSeparator1.setBounds(0, 302, 650, 10);

        jButton5.setText("Logar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton5);
        jButton5.setBounds(539, 363, 70, 30);

        jbPesquisarAnimal.setText("Pesquisar Animal");
        jbPesquisarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarAnimalActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbPesquisarAnimal);
        jbPesquisarAnimal.setBounds(10, 50, 190, 40);

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbSair);
        jbSair.setBounds(30, 370, 70, 30);

        jmSobre.setText("Sobre");
        jmSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSobre);

        jmAjuda.setText("Ajuda");
        jmAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAjudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbVerRelatórioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerRelatórioActionPerformed
        try {
            // TODO add your handling code here:
            Modelo.ModeloRelatorios relatorio = new ModeloRelatorios();
            relatorio.relatorioAnimal();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaVeterinario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaVeterinario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(TelaVeterinario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbVerRelatórioActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jbPesquisarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarAnimalActionPerformed
        // TODO add your handling code here:
        try {
        ModeloAnimal animal = new ModeloAnimal();
        ModeloCliente cliente = new ModeloCliente();
        Controle.ControleAnimal control = new ControleAnimal();
        Controle.ControleCliente controlC = new ControleCliente();
        String cpf, nomeAnimal;
            cpf=JOptionPane.showInputDialog(null, "Digite o CPF do cliente");
            if(controlC.verificarCPF(cpf)){
            nomeAnimal=JOptionPane.showInputDialog(null, "Digite o nome do Animal");
            if(control.verificarNome(nomeAnimal)){
            cliente = controlC.consultarCliente(cpf);
            animal = control.consultarAnimal(cliente.getCpf(), nomeAnimal);
            TelaAlteracaoAnimal telaAlteracaoAnimal = new TelaAlteracaoAnimal();
            telaAlteracaoAnimal.inserirDados(cliente, animal);
            telaAlteracaoAnimal.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Animal não cadastrado");
            }
            }
            else{
                JOptionPane.showMessageDialog(null, "Cliente não cadastrado");
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbPesquisarAnimalActionPerformed

    private void jmSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSobreMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "SISTEMA DE GERENCIAMENTO DE UMA CLÍNICA VETERINÁRIA \n\n"
                + "Sistema criado para gerenciamento de funcionário,veterinário, cliente e animal\n"
                + "de uma clinica, tem como principais funções insersão, exclusão, alteração e pequisa\n"
                + "sobre funcionário, cliente e animal. O Sistemas também possibilita marcar consulta\n"
                + "e gerenciar o estoque da clínica.\n");
    }//GEN-LAST:event_jmSobreMouseClicked

    private void jmAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAjudaMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"PESQUISAR ANIMAL - Pesquisa por um animal no sistema.\n"
                + "VER CONSULTA - Mostra as consultas marcadas.\n"
                + "VER RELATÓRIO - Mostra os relatórios.");
    }//GEN-LAST:event_jmAjudaMouseClicked

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbPesquisarAnimal;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbVerRelatório;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmSobre;
    // End of variables declaration//GEN-END:variables
}
